using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Text;
using Godot;

[Tool]
public partial class ToppingProfileExporter : EditorScript
{
    private const string SourceNodeName = "ToppingProfilesSource";
    private const string OutputPath = "res://Shared/ToppingShapeData.generated.cs";

    public override void _Run()
    {
        var sceneRoot = EditorInterface.Singleton.GetEditedSceneRoot();
        if (sceneRoot == null)
        {
            GD.PushError("No edited scene root found.");
            return;
        }

        var sourceRoot = sceneRoot.FindChild(SourceNodeName, true, false) as Node3D;
        if (sourceRoot == null)
        {
            GD.PushError($"Could not find a Node3D named '{SourceNodeName}' in the edited scene.");
            return;
        }

        var profiles = new List<ToppingShapeProfile>();
        foreach (var child in sourceRoot.GetChildren())
        {
            if (child is not Node3D toppingRoot)
            {
                continue;
            }

            if (!TryBuildProfile(toppingRoot, out var profile))
            {
                continue;
            }

            profiles.Add(profile);
        }

        if (profiles.Count == 0)
        {
            GD.PushError($"'{SourceNodeName}' does not contain any child topping roots with meshes.");
            return;
        }

        var output = BuildGeneratedFile(profiles);
        var absolutePath = ProjectSettings.GlobalizePath(OutputPath);
        Directory.CreateDirectory(Path.GetDirectoryName(absolutePath)!);
        File.WriteAllText(absolutePath, output, Encoding.UTF8);
        GD.Print($"Topping shape data exported to {OutputPath}");
    }

    private static bool TryBuildProfile(Node3D toppingRoot, out ToppingShapeProfile profile)
    {
        var meshes = new List<MeshInstance3D>();
        CollectMeshNodes(toppingRoot, meshes);
        if (meshes.Count == 0)
        {
            profile = default;
            return false;
        }

        var hasBounds = false;
        var min = Vector3.Zero;
        var max = Vector3.Zero;

        foreach (var meshNode in meshes)
        {
            if (meshNode.Mesh == null)
            {
                continue;
            }

            var worldAabb = meshNode.GlobalTransform * meshNode.Mesh.GetAabb();
            if (!hasBounds)
            {
                min = worldAabb.Position;
                max = worldAabb.End;
                hasBounds = true;
                continue;
            }

            min = new Vector3(
                MathF.Min(min.X, worldAabb.Position.X),
                MathF.Min(min.Y, worldAabb.Position.Y),
                MathF.Min(min.Z, worldAabb.Position.Z)
            );
            max = new Vector3(
                MathF.Max(max.X, worldAabb.End.X),
                MathF.Max(max.Y, worldAabb.End.Y),
                MathF.Max(max.Z, worldAabb.End.Z)
            );
        }

        if (!hasBounds)
        {
            profile = default;
            return false;
        }

        var size = max - min;
        var halfWidth = MathF.Max(0.05f, size.X * 0.5f);
        var halfDepth = MathF.Max(0.05f, size.Z * 0.5f);
        var thickness = MathF.Max(0.04f, size.Y);
        var footprint = MathF.Max(0.01f, size.X * size.Z);
        var flatness = Math.Clamp((MathF.Max(size.X, size.Z) / thickness) * 0.08f, 0f, 2f);
        var mass = MathF.Max(0.35f, footprint * thickness * 2.5f);
        var friction = Math.Clamp(0.78f + flatness * 0.08f, 0.78f, 0.97f);
        var edgeGrip = Math.Clamp(0.82f + flatness * 0.12f, 0.82f, 1.12f);

        profile = new ToppingShapeProfile(
            toppingRoot.Name,
            halfWidth,
            halfDepth,
            thickness,
            mass,
            friction,
            edgeGrip
        );
        return true;
    }

    private static void CollectMeshNodes(Node node, List<MeshInstance3D> meshes)
    {
        if (node is MeshInstance3D meshNode)
        {
            meshes.Add(meshNode);
        }

        foreach (var child in node.GetChildren())
        {
            if (child is Node childNode)
            {
                CollectMeshNodes(childNode, meshes);
            }
        }
    }

    private static string BuildGeneratedFile(List<ToppingShapeProfile> profiles)
    {
        var builder = new StringBuilder();
        builder.AppendLine("// Auto-generated by ToppingProfileExporter.cs");
        builder.AppendLine("public static partial class ToppingShapeData");
        builder.AppendLine("{");
        builder.AppendLine("    public static ToppingShapeProfile GetProfile(string name)");
        builder.AppendLine("        => name switch");
        builder.AppendLine("        {");

        foreach (var profile in profiles)
        {
            builder.AppendLine(
                $"            \"{profile.Name}\" => new ToppingShapeProfile(\"{profile.Name}\", {Format(profile.HalfWidth)}f, {Format(profile.HalfDepth)}f, {Format(profile.Thickness)}f, {Format(profile.Mass)}f, {Format(profile.Friction)}f, {Format(profile.EdgeGrip)}f),"
            );
        }

        builder.AppendLine("            _ => Default,");
        builder.AppendLine("        };");
        builder.AppendLine("}");
        return builder.ToString();
    }

    private static string Format(float value)
        => value.ToString("0.######", CultureInfo.InvariantCulture);
}
