// Auto-generated by LooseItemExporter.cs
public static partial class LooseItemData
{
    public static readonly LooseItemDefinition[] Items =
    [
        new LooseItemDefinition("loose items", 0f, 0f, 0f, -0f, 0f, 0f, 1f, 1f, 1f, 149.1504f, 8.995167f, -0.382106f, 14.1249f)
    ];
}
